In [ ]:
# NOTEBOOK 1: DATA PREPARATION & CLEANING

In [ ]:
## 1. Setup - Import Libraries and Mount Google Drive
# Import the necessary libraries
import pandas as pd
import numpy as np

# Mount your Google Drive to access files
from google.colab import drive
drive.mount('/content/drive')

print("Libraries imported and Google Drive mounted successfully.")

Mounted at /content/drive
Libraries imported and Google Drive mounted successfully.

In [ ]:
## 2. Load the Dataset
raw_file_path = '/content/drive/MyDrive/Advanced Retail Analytics project/Superstore.csv'
# Load the CSV file into a pandas DataFrame
try:
    df = pd.read_csv(raw_file_path, encoding='windows-1252') # This encoding often works for this dataset
    print("Dataset loaded successfully.")
    print(f"The dataset has {df.shape[0]} rows and {df.shape[1]} columns.")
except FileNotFoundError:
    print(f"Error: The file was not found at {raw_file_path}")
    print("Please check the file path and make sure the file is uploaded to your Google Drive.")

Dataset loaded successfully.
The dataset has 9994 rows and 21 columns.

In [ ]:
## 3. Initial Data Exploration (Data Profiling)
# Display basic information about the DataFrame
print("\n--- Data Info ---")
df.info()

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [ ]:
# Check for missing values in each column
print("\n--- Missing Values Count ---")
print(df.isnull().sum())

--- Missing Values Count ---
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
# Check for duplicate rows
print(f"\n--- Duplicate Rows ---")
print(f"Number of duplicate rows: {df.duplicated().sum()}")

--- Duplicate Rows ---
Number of duplicate rows: 0

In [ ]:
# Display the first 5 rows to get a feel for the data
print("\n--- First 5 Rows ---")
display(df.head())

--- First 5 Rows ---

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
## 4. Data Cleaning and Transformation
# --- 4.1. Handle Duplicates ---
# We found some duplicate rows, let's remove them.
df.drop_duplicates(inplace=True)
print(f"Removed duplicate rows. New shape: {df.shape}")

Removed duplicate rows. New shape: (9994, 21)

In [ ]:
# --- 4.2. Standardize Column Names ---
# Good practice to make column names consistent (e.g., lowercase with underscores).
df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')
print("\nColumn names standardized.")
print(df.columns)

Column names standardized.
Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

In [ ]:
# --- 4.3. Fix Data Types ---
# Convert 'order_date' and 'ship_date' to datetime objects safely
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
df['ship_date'] = pd.to_datetime(df['ship_date'], errors='coerce')

print("\n'order_date' and 'ship_date' converted to datetime objects.")

'order_date' and 'ship_date' converted to datetime objects.

In [ ]:
# --- 4.4. Handle Missing Values ---
# The 'postal_code' column is the only one with missing values.
# Since it's a numeric code, a simple fill with 0 might be misleading.
# Let's convert it to a string and fill with 'N/A' to signify missing information.
df['postal_code'] = df['postal_code'].astype('Int64').astype(str).fillna('N/A')
print("\nMissing postal codes handled.")

Missing postal codes handled.

In [ ]:
## 5. Feature Engineering (Optional but Recommended)
# -----------------------------------------------------------------------------
# Creating new columns from existing data can be very useful for analysis.

# --- 5.1. Extract Time-Based Features ---
# These will be useful for time series analysis and EDA.
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_weekday'] = df['order_date'].dt.day_name()

# --- 5.2. Calculate Shipping Time ---
# This could be a useful metric for operational analysis.
df['shipping_time_days'] = (df['ship_date'] - df['order_date']).dt.days

print("\nNew features created: 'order_year', 'order_month', 'order_weekday', 'shipping_time_days'")
display(df.head())

New features created: 'order_year', 'order_month', 'order_weekday', 'shipping_time_days'

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sub_category,product_name,sales,quantity,discount,profit,order_year,order_month,order_weekday,shipping_time_days
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,Tuesday,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,Tuesday,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,Sunday,4
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,Sunday,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,Sunday,7

In [ ]:
print("\n--- Final Data Info ---")
df.info()

--- Final Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   row_id              9994 non-null   int64
 1   order_id            9994 non-null   object
 2   order_date          9994 non-null   datetime64[ns]
 3   ship_date           9994 non-null   datetime64[ns]
 4   ship_mode           9994 non-null   object
 5   customer_id         9994 non-null   object
 6   customer_name       9994 non-null   object
 7   segment             9994 non-null   object
 8   country             9994 non-null   object
 9   city                9994 non-null   object
 10  state               9994 non-null   object
 11  postal_code         9994 non-null   object
 12  region              9994 non-null   object
 13  product_id          9994 non-null   object
 14  category            9994 non-null   object
 15  sub_category        9994 non-null   object
 16  product_name        9994 non-null   object
 17  sales               9994 non-null   float64
 18  quantity            9994 non-null   int64
 19  discount            9994 non-null   float64
 20  profit              9994 non-null   float64
 21  order_year          9994 non-null   int32
 22  order_month         9994 non-null   int32
 23  order_weekday       9994 non-null   object
 24  shipping_time_days  9994 non-null   int64
dtypes: datetime64[ns](2), float64(3), int32(2), int64(3), object(15)
memory usage: 1.8+ MB

In [ ]:
# Define the path for the cleaned data file in your Google Drive
cleaned_file_path = '/content/drive/MyDrive/Advanced Retail Analytics project/cleaned_superstore.csv'

# Save the cleaned DataFrame to a new CSV file
df.to_csv(cleaned_file_path, index=False)

print(f"\nCleaned data successfully saved to: {cleaned_file_path}")

Cleaned data successfully saved to: /content/drive/MyDrive/Advanced Retail Analytics project/cleaned_superstore.csv